name: test6666

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

  
env:
  USE_CACHE: yes
  BUILD_CONFIGURATIONS: Release,Debug
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}


jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: 设置默认值
        run: |
          $use_cache = "${{ github.event.inputs.use_cache || 'yes' }}"
          $build_configurations = "${{ github.event.inputs.build_configurations || 'Release,Debug' }}"
          echo "USE_CACHE=$use_cache" >> $env:GITHUB_ENV
          echo "BUILD_CONFIGURATIONS=$build_configurations" >> $env:GITHUB_ENV
   
          
          echo "use_cache1: $use_cache"
          echo "build_configurations1: $build_configurations"
          
          echo "use_cache2:${{ github.event.inputs.use_cache }}"
          echo "build_configurations2:${{ github.event.inputs.build_configurations }}"
          
        shell: pwsh
