name: Build Clients

on:
  workflow_dispatch:

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install specific Go version
        run: |
          wget https://golang.org/dl/go1.21.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go version

      - name: Set up Go environment
        run: |
          echo "export PATH=\$PATH:/usr/local/go/bin" >> $GITHUB_ENV

      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Build Go client
        working-directory: ./clients/go_wcf_http
        run: |
          export GOOS=windows
          export GOARCH=amd64
          go build -ldflags="-s -w" -o go_wcf_http3.9.10.27.exe main.go

      - name: Package Go client
        run: |
          mkdir -p temp/go
          mv clients/go_wcf_http/go_wcf_http3.9.10.27.exe temp/go/

      - name: Package all clients
        run: |
          mkdir -p packages
          cd temp
          for dir in */; do
            zip -r "../packages/${dir%/}.zip" "$dir"
          done
          cd ..
          ls packages
