name: test6666

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' 

      
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置默认值
        run: |
          echo "USE_CACHE=${{ github.event.inputs.use_cache || 'yes' }}" >> $GITHUB_ENV
          echo "BUILD_CONFIGS=${{ github.event.inputs.build_configurations || 'Release,Debug' }}" >> $GITHUB_ENV
          echo "Program Version: $use_cache"
          echo "WeChat Version: $build_configurations"
        shell: pwsh
     
