name: test6666

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:
    inputs:
      use_cache:
        description: 'Use cache'
        required: false
        default: 'yes'
      build_configurations:
        description: 'Build configurations'
        required: false
        default: 'Release,Debug'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: 设置默认值
        run: |
          # $use_cache = "${{ github.event.inputs.use_cache || 'yes' }}"
          # $build_configurations = "${{ github.event.inputs.build_configurations || 'Release,Debug' }}"

          # echo "USE_CACHE=$use_cache" >> $env:GITHUB_ENV
          # echo "BUILD_CONFIGURATIONS=$build_configurations" >> $env:GITHUB_ENV


          echo "USE_CACHE=${{ github.event.inputs.use_cache || 'yes' }}" >> $GITHUB_ENV
          echo "BUILD_CONFIGURATIONS=${{ github.event.inputs.build_configurations || 'Release,Debug' }}" >> $GITHUB_ENV
          
          echo "use_cache1: $use_cache"
          echo "build_configurations1: $build_configurations"
          
        shell: pwsh
